### PR TITLE
Update constants.json

### PR DESCRIPTION
**Pull request by jpigla**
Correct translation for Darkmode. Light means light (Licht) ("turn the lights on"), but is not the correct translation in the context of Darkmode. Better English translation would be "bright" and "dark".

### CODE REVIEW

**Review by miurla — APPROVED** [review]
Since this is an automatic translation by LLM, it seems to have been mistranslated without context. Thank you for the correction, as before!

Danke! 🌞

**Comment by miurla** [comment]
FYI: @Cs4K1Sr4C

**Comment by Cs4K1Sr4C** [comment]
I think I will implement a simple terminal command into ATi18n as a "corrector" mechanism which will allow the user to select a key's value for manual correction.

Thank you for the information! 🙏 @jpigla @miurla

**Comment by Cs4K1Sr4C** [comment]
Or just a dictionary... 😆 🤣 😅

**Pull request merged**
