### PR TITLE
Create README_ES-ES.md

### PR DESCRIPTION
**Pull request by johnfelipe**

### CODE REVIEW

**Comment by miurla** [comment]
@johnfelipe 

PR Thank you! 👍 
However, like many other repositories, I don't intend to make the Readme a translation target. The Readme isn't subject to automatic translation and it also increases the maintenance cost. 
What do you think?

**Comment by johnfelipe** [comment]
> @johnfelipe
> 
> PR Thank you! 👍 However, like many other repositories, I don't intend to make the Readme a translation target. The Readme isn't subject to automatic translation and it also increases the maintenance cost. What do you think?

yes dont worry, that is for spanish users

**Comment by miurla** [comment]
If we add this Spanish Readme, I would have to keep translating and updating it whenever there are changes to the original Readme, which I want to avoid. Is it okay if I close this PR?

**Comment by johnfelipe** [comment]
No I want to contribute with that for Spanish users
I will PR each week that .MD file

**Comment by miurla** [comment]
Okay, I understand. Please handle it when there are changes to the Readme. 
Thank you for your contribution.

**Pull request merged**
